### ISSUE TITLE
[bug] windows is broke

### ISSUE THREAD

**Issue by tribhuwan-kumar** [mediar-ai/screenpipe#1582]
**describe the bug**
brief description of the bug.

```rust
error[E0433]: failed to resolve: use of undeclared crate or module `core_foundation`
 --> screenpipe-core\src\operator\tree_search.rs:3:5
  |
3 | use core_foundation::array::CFArray;
  |     ^^^^^^^^^^^^^^^ use of undeclared crate or module `core_foundation`

error[E0432]: unresolved import `accessibility`
 --> screenpipe-core\src\operator\tree_search.rs:2:5
  |
2 | use accessibility::{AXAttribute, AXUIElement, AXUIElementAttributes, Error};
  |     ^^^^^^^^^^^^^ use of undeclared crate or module `accessibility`

error[E0432]: unresolved import `thiserror`
 --> screenpipe-core\src\operator\errors.rs:1:5
  |
1 | use thiserror::Error;
  |     ^^^^^^^^^ use of undeclared crate or module `thiserror`

error: cannot find attribute `error` in this scope
 --> screenpipe-core\src\operator\errors.rs:5:7
  |
5 |     #[error("Element not found: {0}")]
  |       ^^^^^

error: cannot find attribute `error` in this scope
 --> screenpipe-core\src\operator\errors.rs:8:7
  |
8 |     #[error("Operation timed out: {0}")]
  |       ^^^^^

error: cannot find attribute `error` in this scope
  --> screenpipe-core\src\operator\errors.rs:11:7
   |
11 |     #[error("Permission denied: {0}")]
   |       ^^^^^

error: cannot find attribute `error` in this scope
  --> screenpipe-core\src\operator\errors.rs:14:7
   |
14 |     #[error("Platform-specific error: {0}")]
   |       ^^^^^

error: cannot find attribute `error` in this scope
  --> screenpipe-core\src\operator\errors.rs:17:7
   |
17 |     #[error("Unsupported operation: {0}")]
   |       ^^^^^

error: cannot find attribute `error` in this scope
  --> screenpipe-core\src\operator\errors.rs:20:7
   |
20 |     #[error("Unsupported platform: {0}")]
   |       ^^^^^

error: cannot find attribute `error` in this scope
  --> screenpipe-core\src\operator\errors.rs:23:7
   |
23 |     #[error("Invalid argument: {0}")]
   |       ^^^^^

error: cannot find attribute `error` in this scope
  --> screenpipe-core\src\operator\errors.rs:26:7
   |
26 |     #[error("Internal error: {0}")]
   |       ^^^^^

error[E0407]: method `get_element_by_id` is not a member of trait `AccessibilityEngine`
  --> screenpipe-core\src\operator\platforms\windows.rs:21:5
   |
21 | /     fn get_element_by_id(&self, _id: &str) -> Result<UIElement, AutomationError> {
22 | |         Err(AutomationError::UnsupportedPlatform(
23 | |             "Windows implementation is not yet available".to_string(),
24 | |         ))
25 | |     }
   | |_____^ not a member of trait `AccessibilityEngine`

   Compiling webrtc-vad v0.4.0
   Compiling crossbeam-channel v0.5.14
   Compiling widestring v1.1.0
error[E0046]: not all trait items implemented, missing: `find_element`
  --> screenpipe-core\src\operator\platforms\windows.rs:16:1
   |
16 |   impl AccessibilityEngine for WindowsEngine {
   |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing `find_element` in implementation
   |
  ::: screenpipe-core\src\operator\platforms\mod.rs:18:5
   |
18 | /     fn find_element(
19 | |         &self,
20 | |         selector: &Selector,
21 | |         root: Option<&UIElement>,
22 | |     ) -> Result<UIElement, AutomationError>;
   | |____________________________________________- `find_element` from trait

error[E0050]: method `get_text` has 1 parameter but the declaration in trait `UIElementImpl::get_text` has 2
   --> screenpipe-core\src\operator\platforms\windows.rs:148:17
    |
148 |     fn get_text(&self) -> Result<String, AutomationError> {
    |                 ^^^^^ expected 2 parameters, found 1
    |
   ::: screenpipe-core\src\operator\element.rs:39:17
    |
39  |     fn get_text(&self, max_depth: usize) -> Result<String, AutomationError>;
    |                 ----------------------- trait requires 2 parameters

   Compiling screenpipe-vision v0.2.62 (C:\Users\eirae\Downloads\app\screenpipe\screenpipe-vision)
   Compiling ntapi v0.4.1
error[E0061]: this function takes 0 arguments but 2 arguments were supplied
  --> screenpipe-core\src\operator\platforms\mod.rs:55:28
   |
55 |         return Ok(Box::new(windows::WindowsEngine::new(
   |                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
56 |             use_background_apps,
   |             ------------------- unexpected argument #1 of type `bool`
57 |             activate_app,
   |             ------------ unexpected argument #2 of type `bool`
   |
note: associated function defined here
  --> screenpipe-core\src\operator\platforms\windows.rs:9:12
   |
9  |     pub fn new() -> Result<Self, AutomationError> {
   |            ^^^
help: remove the extra arguments
   |
56 -             use_background_apps,
56 +             )?));
   |

   Compiling claxon v0.4.3
warning: unused import: `std::os::windows::process::CommandExt`
  --> screenpipe-core\src\pipes.rs:41:5
   |
41 | use std::os::windows::process::CommandExt;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: `#[warn(unused_imports)]` on by default

   Compiling whisper-rs v0.14.2 (https://github.com/tazz4843/whisper-rs.git?rev=e0597486400ec436669e6ee3d8cc94b3859355f5#e0597486)
   Compiling cpal v0.15.3 (https://github.com/Kree0/cpal.git?branch=master#e851e41b)
   Compiling audio-core v0.2.0
Some errors have detailed explanations: E0046, E0050, E0061, E0407, E0432, E0433.
For more information about an error, try `rustc --explain E0046`.
warning: `screenpipe-core` (lib) generated 1 warning
error: could not compile `screenpipe-core` (lib) due to 15 previous errors; 1 warning emitted
warning: build failed, waiting for other jobs to finish...
```

**system info**
- os: [e.g. macos 10.15.7, windows 10, ubuntu 20.04]
- screenpipe version: [e.g. 1.2.3]

**additional context**
add any other context, screenshots, or error logs here.

- you can find logs in `~/.screenpipe` on macOS/Linux, and `%APPDATA%\.screenpipe` on Windows.
- you can get app logs by right clicking in the app background and clicking the console tab.

**Comment by divanshu-go** [comment]
@louis030195 @tribhuwan-kumar 

same for linux

**Comment by tribhuwan-kumar** [comment]
fixing it!!

**Comment by louis030195** [comment]
fixed

**Comment by tribhuwan-kumar** [comment]
> fixed

@louis030195 

not fixed :(

```rust
   Compiling screenpipe-core v0.2.62 (C:\Users\eirae\Downloads\app\screenpipe\screenpipe-core)
error[E0407]: method `get_element_by_id` is not a member of trait `AccessibilityEngine`
  --> screenpipe-core\src\operator\platforms\windows.rs:21:5
   |
21 | /     fn get_element_by_id(&self, _id: &str) -> Result<UIElement, AutomationError> {
22 | |         Err(AutomationError::UnsupportedPlatform(
23 | |             "Windows implementation is not yet available".to_string(),
24 | |         ))
25 | |     }
   | |_____^ not a member of trait `AccessibilityEngine`
```
could you add these lines right next to it?
 
```rust
    #[cfg(target_os = "windows")]
    fn get_element_by_id(&self, _id: &str) -> Result<UIElement, AutomationError>;
```
https://github.com/mediar-ai/screenpipe/blob/3359116546ad38870e6876c750c0d2f91d896043/screenpipe-core/src/operator/platforms/mod.rs#L9
